### ISSUE TITLE
Update governance script to support upgrading contracts

### ISSUE THREAD

**Issue by asaj** [abacus-network/abacus-monorepo#1008]
Add a check in the checker to verify that the implementation contract address matches what's pointed to by the `UpgradeBeacon`.

If not, emit a contract implementation violation.

**Comment by yorhodes** [comment]
we have this
https://github.com/abacus-network/abacus-monorepo/blob/bbf553caf7089706de0931ea1a9c2857e5dcb924/typescript/sdk/src/deploy/AbacusAppChecker.ts#L56
