### ISSUE TITLE
Build the demo application

### ISSUE THREAD

**Issue by nambrot** [abacus-network/abacus-monorepo#244]
Blocked on https://github.com/bridge-buddies/optics-monorepo/issues/241 and https://github.com/bridge-buddies/optics-monorepo/issues/243

- Write from any router to any other router
- Keep messages in contract state
- showscase a local unit test https://github.com/bridge-buddies/optics-monorepo/issues/249
- showcase a deployment to testnet #241 
- showcase building a UI for it with #243

**Comment by asaj** [comment]
We decided not to do this
