### ISSUE TITLE
Specify API between Inbox and ValidatorManager in spec

### ISSUE THREAD

**Issue by nambrot** [abacus-network/abacus-monorepo#315]
An implementation of a multisignature Validator is incompatible with the current API between the inbox and the validator manager as the inbox would not be able to pass a single bytes32 to the ValidatorManager anymore. The spec should be changed so that it can support all future Validator signature schemes.

I imagine this means that the Validator becomes a permissioned role (via the ValidatorManager) on the Inbox that can call `checkpoint`, i.e. a push instead of a pull model for the Inbox. The Validator manager would just expose `validator(uint32 domain)(address)` function that returns the address of the validator that the Inbox can call

**Comment by asaj** [comment]
We're good on this front
