### ISSUE TITLE
Bundle Inbox#checkpoint with message processing

### ISSUE THREAD

**Issue by nambrot** [abacus-network/abacus-monorepo#346]
As per the recent decision to not subsidize system processing, applications will need to pay for inbox checkpointing on the destination chain. this ticket emcompasses the following work (feel free to change the names):

- Add a function `InboxValidatorManager#checkpointAndProcess` which (after quorum check) basically just calls the existing `InboxValidatorManager#checkpoint` function and then `Inbox.process` to save the intrinsic gas cost
- It support processing a batch of messages but not revert when the handling of a message fails

Additionally:
- Add a `onlyValidatorManager` function to `Inbox` called `directProcess` which has the same signature as `process` except it also takes a root as an argument and then verifies the merkle proof against that (instead of a stored checkpoint)
- Add a function `InboxValidatorManager#directProcess` which (after quorum check) calls `directProcess` on the batch of passed in messages

Actually, one should go one step further and not even store the checkpoint in storage at all, instead verify the signatures for a checkpoint and then process messages directly against it.

This ticket now exclusively reflects the scope to add these latency/gas saving combinations of checkpointing/message processing to the contracts and creates https://github.com/abacus-network/abacus-monorepo/issues/472 for the agent specific changes

**Comment by asaj** [comment]
Noting that we've agreed to remove the caching of checkpoints on the Inbox entirely

**Comment by asaj** [comment]
Played around with some gas profiling in asaj/inbox-checkpoints

You can see the results here:
https://docs.google.com/spreadsheets/d/1mHiCQWd7Pu5o80dAXgQrtdlAV4VyMRqlJdOc5hQSX0s/edit#gid=2099625087

**Comment by tkporter** [comment]
Satisfied by #523
