### ISSUE TITLE
[Investigate] Demo application scope

### ISSUE THREAD

**Issue by nambrot** [abacus-network/abacus-monorepo#350]
Idea: Something similar to r/place where users can collaboratively color pixels together

Problems:
- Dicks
- Spam

Spec:
- Each chain is it's own layer with its own color that gets merged on the UI
  - 1 layer each for RGB
  - 1 layer for opacity
  - Not every chain will have state, but that is ok, because only some chains will probably have enough testnet funds to actually do process all the messages
- The canvas is represented as an mapping of indicies to uint256 with a total byte length of height x length of the canvas.

```solidity
mapping(uint=>uint256) pixels
uint width;
uint height;

function setPixel(uint x, uint y, bool set) {
  uint index = y * width + x;
  uint segment = index / 256;
  uint indexWithinSegment = index % 256;
  uint256 currentValue = pixels[segment];
  uint256 mask = 2**indexWithinSegment;
  uint256 targetValue = set ? mask | currentValue : ~mask & currentValue;
  pixels[segment] = targetValue;
}

```

**Comment by asaj** [comment]
We decided not to do this, closing
