### ISSUE TITLE
More efficient agent Docker image building in CI

### ISSUE THREAD

**Issue by tkporter** [abacus-network/abacus-monorepo#358]
At the moment, we're using the GitHub cache as an image cache ([see here](https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache)). This was a quick and dirty solution, and it's unclear whether this is the best caching mechanism or how well it's actually using a cache. It also feels like there is a lot of room for improvement on our Dockerfile. The scope of this is pretty open, but ideally we'd make some changes to not have to wait more than a few minutes for an image to build

**Comment by Eadword** [comment]
Couple of thoughts on this right now:
1. we already have layer caching working so we can use the method described [here](https://blog.mgattozzi.dev/caching-rust-docker-builds/) to create a dummy layer with all of the dependencies (so as long as there are no dependency changes it won't rebuild them)
2. the docker image does cache locally using a docker cache volume, we could just have this volume get cached using the normal cache action, this has the benefit of not causing a total-rebuild if the cargo.toml/cargo.lock changes.
