### ISSUE TITLE
Proxy InboxValidatorManager for more efficient deploys

### ISSUE THREAD

**Issue by nambrot** [abacus-network/abacus-monorepo#365]
Abacus core deployments are relatively expensive. One way to easily save gas is to use EIP1667 proxies for the InboxValidatorManager

**Comment by asaj** [comment]
Also for `Inboxes`, no?

**Comment by nambrot** [comment]
I thought you made the point that being able to upgrade implementations is important for Inboxes in a way that is less so for the InboxValidatorManager?

**Comment by nambrot** [comment]
Yes 1167.

Yeah maybe its easier to just use beacon proxy pattern, but the original point was that using 1167 is technically the minimal approach as it preserves the current property that InboxValidatorManagers are not upgradable. It's less of a need since governance can always upgrade via repointing to new InboxValidatorManager contracts on the Inbox, so it seems unnecessary to support upgrading

**Comment by yorhodes** [comment]
After spending far too much time on this, I realized that `_domain` and `_domainHash` are `immutable` on `MultisigValidatorManager`. Therefore, "cloning runtime bytecode" with [EIP-1167](https://eips.ethereum.org/EIPS/eip-1167) only works if we move `_domain`/`_domainHash` out of bytecode and into storage. However, `_domainHash` is used by `_recoverCheckpointSigner` (used in `isQuorum`), which implies at least one additional `SLOAD` for `InboxValidatorManager.process` (in addition to the extra call from proxying). 

Posting back of napkin math from chat with @asaj offline
`InboxValidatorManager` costs `1539485` to deploy
Minimal proxy is at least `41000` (`32000` static + `200` * `45` bytes)
`savingsPerChain(numberOfChains) = 1539485 * numberOfChains - (1539485 + 41000 * numberOfChains)`
Even with 25 chains, at current ETH prices ~$1823, savings are less than $100 on mainnet. 

One day I will learn the lesson of premature optimization.
