### ISSUE TITLE
Think about v1 Interchain Gas Payments

### ISSUE THREAD

**Issue by nambrot** [abacus-network/abacus-monorepo#368]
We have a v0 of Interchain gas payments that doesn't have a lot of nuance as to how a user might want to express the trade-offs of how a message should be processed on the receiving chain. Some downsides include:

- How should the buffer/surplus of the payment get allocated? I.e. how does a user express that they want to pay the max gas price at the current relative gas token price vs. the buffer is there to just account for volatility in the relative price, but they don't want to pay a high gas price
- The user is unable to express that they would like to wait a certain amount of time/contribute to be part of a amortized checkpoint (both outbox and inbox)
- The user is unable to pay for derivative message processing.
- Users can't specify where the excess gas payments can be refunded to

A v1 doesn't have to address all of these issues, but should be a meaningful improvement at a reasonable cost

**Comment by tkporter** [comment]
done
