### ISSUE TITLE
Make `MultiProvider` API more defensive

### ISSUE THREAD

**Issue by yorhodes** [abacus-network/abacus-monorepo#394]
Allow users to instantiate with fewer networks than app abstraction
Ensure signer exists when using eth_send
Ensure provider exists when using eth_call

**Comment by nambrot** [comment]
MultiProvider should have methods to get the signer https://github.com/abacus-network/abacus-monorepo/pull/343#discussion_r866061714

**Comment by yorhodes** [comment]
related https://github.com/abacus-network/abacus-monorepo/issues/462

**Comment by jmrossy** [comment]
@yorhodes Can you clarify how 462 is related here? I can see the value of ChainConnection being a provider but not so sure how it relates to this
