### ISSUE TITLE
Message Explorer v1 Design

### ISSUE THREAD

**Issue by nambrot** [abacus-network/abacus-monorepo#414]
To aid in debugging for both developers, and for the users of Abacus applications, Abacus should provide a message explorer that indexes messages and shows their processing status, associated gas payments etc.

There is likely some 80/20 work that is doable here with the use of ContractSync that just stashes messages in a "proper" DB instead of an embedded one. This ticket should represent the investigation of how much work that would be to extract such a service out from the rust codebase

**Comment by nambrot** [comment]
Initial draft scope:

- Should be run from the relayer (default one)
- Should be done with a simple SQL adapter in mind (dont know what canonical in Rustland)
- Should be graceful to no DB to be configured
- Indexes messages, gas payments, checkpoints (individual signatures), and relayer processing status in a normalized schema (see below)   
- Needs to be resilient to restarts
- Needs to be able to reindex from genesis with a new DB

Initially considered out of scope:
- Serving the data in an API
  - We may want to consider a out of the box solution a la https://www.moesif.com/blog/graphql/technical/Ways-To-Add-GraphQL-To-Your-Postgres-Database-Comparing-Hasura-Prisma-and-Others/

DB Schema:
- All:
    - Time created
    - Time updated
- Messages
    - Origin
    - Destination
    - Leaf index
    - Sender
    - recipient
    - Message bytes
    - Tx hash
    - Block number
- Gas Payments
    - Leaf index
    - Origin
    - From
    - amount
    - Tx hash
    - Block number
- Checkpoints
    - Signature
    - Validator address
    - Root
    - Index
    - Origin 
- Relaying Status
    - Leaf index
    - Origin
    - Last Error:
        - Null by default
        - If the relayer was not able to process update this field with some semantic information, probably some kind of structured info would be good
            - Processing reverted: ${revert reason}
            - Payment is not sufficient
            - No checkpoints
            - Any other error

**Comment by mattiecnvr** [comment]
A nice to have would be support for filling in new information (like a new column or table) without having to delete the database AND while still maintaining sync with the current state. 

Another nice to have would be to insert information even before the finality window closes and be able to update it if it changes (possibly put a flag on it so API users know it is not considered final yet)

**Comment by mattiecnvr** [comment]
We want the scraping to be built into the relayer for now, it is very important that we are able to get information from the relayer about why messages are not able to be sent.

**Comment by asaj** [comment]
@nambrot I'd propose a different DB schema. Specifically, I'm not sure that it makes sense to separate "Relaying Status" from "Messages". It really only serves to add "Last Error", which seems to try to consolidate a bunch of things that can each be evaluated independently.  

Instead, I would propose we remote "Relaying Status" in favor of adding the following to "Message":
- Processable (whether or not gas estimation on `handle` succeeds
- estimatedGasCost (how much gas we expect it would cost to deliver the message)
- Process tx hash
- Dispatch tx hash (replaces "tx hash")
- Outbox address

I would also consider consolidating "checkpoints" to be per-index (e.g. "validators", not "validator") and adding "count" so that we can query for checkpoints with count >= quorum and index >= msg_index.

This would allow us to easily infer if the message is undeliverable because we don't have a quorum of signatures.

**Comment by asaj** [comment]
I'm actually wondering if something like this could serve as the basis for an omniscient relayer, allowing us to support callbacks with griefing resistance.

IIUC we would just need to add a "dispatchedMessages" field to "messages", as well as exchanges rates at the time of processing, in order to have all of the information we need in one place.

**Comment by asaj** [comment]
> We want the scraping to be built into the relayer for now, it is very important that we are able to get information from the relayer about why messages are not able to be sent.

I'm not sold on this approach, it seems like we should be able to infer everything we want without having the relayer doing the indexing.

@mattiecnvr / @nambrot can you share an example of something that we would *not* be able to infer from the outside?

**Comment by mattiecnvr** [comment]
@tkporter and I were talking about how we could use this data for this exact purpose, and we decided that it is something to keep in mind but maybe not something to plan for yet.

**Comment by mattiecnvr** [comment]
> > We want the scraping to be built into the relayer for now, it is very important that we are able to get information from the relayer about why messages are not able to be sent.
> 
> I'm not sold on this approach, it seems like we should be able to infer everything we want without having the relayer doing the indexing.
> 
> @mattiecnvr / @nambrot can you share an example of something that we would _not_ be able to infer from the outside?

This is not the current approach, see the notion page for current scope. Was going to update tickets after.

**Comment by nambrot** [comment]
> I would also consider consolidating "checkpoints" to be per-index (e.g. "validators", not "validator") and adding "count" so that we can query for checkpoints with count >= quorum and index >= msg_index.
(edit: maybe this isn't actually a useful suggestion?)

> This would allow us to easily infer if the message is undeliverable because we don't have a quorum of signatures

Does the schema I proposed not allow for this?

> @nambrot I'd propose a different DB schema.

IIRC, the original reason to separate out relaying status was to allow multiple relayers to report their status (with the goal of the message explorer being the best channel to get insight into relayer internal state). If you want to view the message explorer as a strict indexer of chain data, then agreed that it would be unnecessary separation. (good call out on the two tx hashes)

**Comment by jmrossy** [comment]
Making as done during sprint planning.
