### ISSUE TITLE
Relayer wallet balance should be observable

### ISSUE THREAD

**Issue by nambrot** [abacus-network/abacus-monorepo#452]

**Comment by Eadword** [comment]
We were talking about creating a debug HTTP API, seems like a good first candidate for that API.

**Comment by nambrot** [comment]
Why is this a good candidate for that API? It actually feels like the opposite to me? It's state that is easily queryable for from the outside world? Why would this metric not update so frequently?

**Comment by mattiecnvr** [comment]
@nambrot It is not a public API, the API will be exposed only within the containers for us to debug.

Metrics only update on the scraping interval of prometheus, so it makes sense to be able to get the instantaneous values at times.

Maybe I misunderstood what you mean by "observable" but I took it to mean that we could get the exact current value when needed.
