### ISSUE TITLE
Consider making `Inbox.process` and `IMessageRecipient.handle` payable

### ISSUE THREAD

**Issue by tkporter** [abacus-network/abacus-monorepo#479]
* Regardless of the potential that processing a message along with native value has for child messages, it may be a desirable feature regardless. It could be used by an app bringing users over to a new chain that want dust to immediately be able to send transactions with. Some token bridges support this and have gotten a lot of praise for the nice UX. Some other cross chain communication protocols also allow this, so feature parity is nice
* Making `Inbox.process` and `IMessageRecipient.handle` payable seems to be an innocuous change that could allow for this feature to be taken advantage of by future apps / relayers

**Comment by asaj** [comment]
Decided not to do this for now per the discussion on #539
