### ISSUE TITLE
Add `onlySelf` modifier to Router.sol

### ISSUE THREAD

**Issue by nambrot** [abacus-network/abacus-monorepo#481]
If one uses the built-in method dispatch via `address(this).call(_message)`, the methods need to be visible which only happens if they are public, but they generally should be authenticated to only be called by the contract iself (i.e. ideally internal), so `Router` should have a modifier that implementors can use.

Something like:

```solidity
modifier onlySelf() {
        require(msg.sender!= address(this), "caller is not self");
        _;
    }
```

**Comment by asaj** [comment]
Per a conversation with @yorhodes and myself this pattern feels like a big footgun and we should avoid recommending it.
