### ISSUE TITLE
Able to send Gelato Relay ForwardRequests in Rust agents

### ISSUE THREAD

**Issue by tkporter** [abacus-network/abacus-monorepo#484]
* In Rust, we should be able to create and send a signed [ForwardRequest](https://docs.gelato.network/developer-products/gelato-relay-sdk/request-types#forwardrequest) to the Gelato Relay API. We'll want to be using payment type "Asynchronous Gas Tank Payment (Type 1)" (more info [here](https://docs.gelato.network/developer-products/gelato-relay-sdk/payment-types)). Some poking around is probably needed in their Typescript SDK [here](https://github.com/gelatodigital/relay-sdks-monorepo) to understand what the HTTP API actually looks like.
* This ticket just encapsulates a friendly Rust interface for interacting with the Gelato relay API when it comes to Type 1 ForwardRequests. Ultimately, we want to be able to send a [ForwardRequest](https://docs.gelato.network/developer-products/gelato-relay-sdk/request-types#forwardrequest) to the Gelato Relay API with calldata that will process a single message, which is tracked in the subsequent task here https://github.com/abacus-network/abacus-monorepo/issues/485

**Comment by tkporter** [comment]
Fixed by https://github.com/abacus-network/abacus-monorepo/pull/511

**Comment by webbhorn** [comment]
This can be done now so I'm gonna close. I think next are #612 / #485
