### ISSUE TITLE
Relayer should use InboxValidatorManager.process and not cache checkpoints on the Inbox

### ISSUE THREAD

**Issue by tkporter** [abacus-network/abacus-monorepo#529]
Following https://github.com/abacus-network/abacus-monorepo/pull/523, the agents require updating to no longer cache checkpoints on the inbox, and to instead provide a signed checkpoint when processing a message.

**Comment by tkporter** [comment]
Some desirable features of the implementation, imo:
1. Keep existing setup where upon learning of a new signed checkpoint at a particular index, any messages that are now processable as a result should be attempted to be processed
2. Keep existing setup where a backlog of messages that have been unable to be processed is kept, and messages in the backlog are occasionally re-evaluated
3. Minimal code changes & small surface area (even if there are more clever designs, we can refactor later)
4. As robust as possible to changes in the validator set -- i.e. messages in the backlog probably shouldn't have a signed checkpoint alongside them in the DB, because if the validator set changes, then the signatures of that signed checkpoint may no longer constitute a quorum

The existing `checkpoint_relayer.rs` has immediate message processing ([see here](https://github.com/abacus-network/abacus-monorepo/blob/main/rust/agents/relayer/src/checkpoint_relayer.rs#L143)), where it will attempt to process all newly processable messages after caching a checkpoint. This is essentially satisfies (1) up above-- we already have the signed checkpoint alongside message proofs, so this can easily be adapted to call the new `InboxValidatorManager.process` for all messages instead of caching the checkpoint once and then calling `Inbox.process` for each mesasge.

The existing `message_processor.rs` contains logic that satisfies (2) where messages in a backlog are reattempted to be processed. The current implementation expects the checkpoint relayer to be going on in the background, as the message processor watches for newly cached checkpoints to process messages against ([see here](https://github.com/abacus-network/abacus-monorepo/blob/main/rust/agents/relayer/src/message_processor.rs#L110)). There is no existing logic in here to fetch signed checkpoints.

My initial naive thinking was along the lines of:
a. Modify `checkpoint_relayer` as described above to use `InboxValidatorManager.process` when immediate message processing is enabled
b. If a message is unable to be processed there (i.e. it reverts), write `(signed checkpoint, merkle proof, message)` to the DB. In the `message_processor` when attempting a message in the backlog, read the relevant data from DB and use it to attempt to call `InboxValidatorManager.process`

This has the obvious downsides of writing a lot of things to storage and it doesn't really satisfy (4).

@webbhorn's suggestion is much better. He said that (for better or worse) we already use the DB kind of as a pub/sub, so we could do something like:
a. Modify `checkpoint_relayer` as described above to use `InboxValidatorManager.process` when immediate message processing is enabled
b. Upon fetching a new signed checkpoint in `checkpoint_relayer`, write the signed checkpoint to the DB. In the `message_processor`, and keep pretty much the exact same logic as now. Instead of checking for the latest cached checkpoint in the inbox, `message_processor` would check the DB for the newest signed checkpoint.

This has one downside in that the signed checkpoint would be persisted in the database. Atm the relayer determines who the validator set is via configuration and not by looking at the state of InboxValidatorManager. So upon changing the validator set, we'd reconfigure the relayer, and upon startup a potentially invalid signed checkpoint will be in the DB. A quick solution to this could be to invalidate the DB entry upon startup.

Thinking about this more, I wonder if rather than using the DB as a pub/sub, we could just use a channel to send new signed checkpoints from the `checkpoint_relayer` to `message_processor`. On the `message_processor` side, we could use https://doc.rust-lang.org/std/sync/mpsc/struct.Receiver.html#method.try_recv to read new signed checkpoints without blocking. I think using the DB for pub/sub purposes is questionable and this wouldn't require us to invalidate the DB entry upon startup. I'm not sure if channels are the absolute best practice in Rust tbh, but from what I've googled I don't see any arguments against using it.

I think it's natural we would rename `checkpoint_relayer` and likely `message_processor` to something more accurate

**Comment by mattiecnvr** [comment]
Channels are based. I love to use them all the time. The only requirement IMO is making sure that the setup for channels does not end up with some really messy spaghetti as it can at time be. There are usually fixes so lmk if you run into a mess threading the threads through and maybe....
