### ISSUE TITLE
Make InterchainGasPaymaster upgradeable

### ISSUE THREAD

**Issue by tkporter** [abacus-network/abacus-monorepo#535]
We should make InterchainGasPaymaster upgradeable so we can later upgrade it to forward payments to Gelato's Gas Tank in the future. This is preferable rather than swapping out the implementation because:
* following #531, InterchainGasPaymasters will be more at the discretion of an application, so we can't expect applications to swap the implementation
* The relayers aren't built in a way in which they will index gas payments from a contract up until some point and then a different contract following that event-- it'll be a lot easier if the indexer just cares about a single address

More context and background:
https://github.com/abacus-network/abacus-monorepo/issues/493

**Comment by asaj** [comment]
For posterity, this was removed from the mainnet alpha milestone because we do not expect to deploy an IGP until post-mainnet launch

**Comment by nambrot** [comment]
Closing this in favor of https://github.com/abacus-network/abacus-monorepo/issues/655
