### ISSUE TITLE
Make HelloWorld a Kathy

### ISSUE THREAD

**Issue by nambrot** [abacus-network/abacus-monorepo#545]
We should leverage the HelloWorld app to generate load on the testnet. Once #514 is done, the `infra` package can deploy it and run a simple script to trigger messages / build a simple k8s cronjob to trigger messages occasionally.

**Comment by asaj** [comment]
@nambrot dupe of #536 ?

**Comment by asaj** [comment]
Closing as dupe of #536, as that's the one in the milestone
