### ISSUE TITLE
Undesirable RetryingProvider behavior

### ISSUE THREAD

**Issue by tkporter** [abacus-network/abacus-monorepo#551]
I ran into some unfortunate behavior while testing #550. There are pretty much 2 main things:
* Upon trying to submit a transaction to process a message, estimating gas will fail if the handler of the message reverts, which is expected behavior. However the RetryingProvider will see this error as an invitation to retry gas estimation a bunch of times, sleeping many seconds along the way. Because of the way the MessageProcessor works, which serially attempts to process messages, this means the MessageProcessor is essentially stuck waiting for the RetryingProvider to finally hit `RetryingProviderError::MaxRequests` (after ~5 retries and a minute or two) before it can attempt to process other transactions.

E.g. some logs for our own test case with kathy where processing reverts if the block hash is odd:
```
2022-06-07T11:37:48.886052Z  WARN abacus_ethereum::retrying: Error in retrying provider, backoff_seconds: 8, retries_remaining: 2, error: (code: -32603, message: Error: VM Exception while processing transaction: reverted with reason string 'block hash is odd', data: None), method: eth_estimateGas
    at chains/abacus-ethereum/src/retrying.rs:98
    in abacus_ethereum::validator_manager::process with .........
```
Eventually sometimes leading to:
```
2022-06-07T09:49:19.417583Z ERROR abacus_ethereum::validator_manager: error: Hit max requests
    at chains/abacus-ethereum/src/validator_manager.rs:95
    in abacus_ethereum::validator_manager::process with ........
```

* It also looks like we can get in a situation where, I believe due to the RetryingProvider, transaction nonces that are too low are submitted on-chain. E.g.:
```
2022-06-07T11:40:51.963374Z  WARN abacus_ethereum::retrying: Error in retrying provider, backoff_seconds: 32, retries_remaining: 0, error: (code: -32000, message: Nonce too low. Expected nonce to be 5 but got 4., data: None), method: eth_sendRawTransaction
    at chains/abacus-ethereum/src/retrying.rs:98
    in abacus_ethereum::validator_manager::process with
```
I could see RetryingProvider and the NonceManagerMiddleware not playing well with each other. We should look into this.

It's hard to know the exact recommendation for what we should do, but having thought about this for 30 seconds I believe it should be something along the lines of:
* Either don't retry when estimating gas when processing, or only retry once
* Consider just retrying fewer times everywhere
* Investigate how we can ensure that correct nonces are used
* Play around with everything more and understand the implications of the RetryingProvider better, coming to a more informed recommendation than the one in this issue :)

**Comment by tkporter** [comment]
This may be interesting https://docs.rs/ethers-providers/latest/ethers_providers/struct.RetryClient.html

**Comment by tkporter** [comment]
The main issue here is that RetryingProvider was created to deal with intermittent RPC provider issues, but this has weird implications when we make `eth_estimateGas` calls when processing messages.

I think the best path forward here is to:
* Reduce the # of retries to 1 (pretty sure the default is 5 right now - this should be 1, and we should make any relevant changes to our k8s infrastructure and `run_locally.sh` to use 1 retry. We should make sure that by setting it to 1 we don't expose ourselves to some awkward off by one issue where the value 1 means that the RPC is only _sent_ once and instead that it means there will be at most 2 RPC attempts (1 being the initial RPC and the next being a retry)
* Iirc the amount of time slept between retries is `2 ^ retryCount` seconds. This is really high. We should bring this down to something more sane at least for the first retry, something < 1s, like a few hundred ms
* Run `run_locally.sh` and see how the relayer behaves. Particularly find `eth_estimateGas` calls that are reverting because the message being processed is reverting (e.g. look for the "block hash is odd" revert reason). Does it seem like failing messages are slowing things down? Is the logging particularly noisy? Feel free to make appropriate logging changes to ensure that this sort of expected behavior isn't making a ton of noise

I don't think we've seen the nonce issues lately, so if you don't observe these in the testnet2/mainnet or even `run_locally` relayer logs, feel free to consider that fixed. I think the modest refactors we've done lately in the relayer fixed this for us

**Comment by mattiecnvr** [comment]
After talking with @webbhorn about some of the issues he ran into with the retrying provider and his new message processor logic my current thoughts are

1) sometimes we want retrying logic at a higher level (i.e. where we area already retrying based on different logic) and therefore don't want automatic retires by the provider at all

2) we can either setup the `RetryClient` that @tkporter mentioned above OR we can look into creating a way to wrap a call to retry it. Not sure which is better without more research, but I am guessing the `RetryClient` is at least halfway decent.
