### ISSUE TITLE
Automatically name known contracts in agent metric confs

### ISSUE THREAD

**Issue by tkporter** [abacus-network/abacus-monorepo#559]
Atm, it doesn't seem like the `metricsConf` (see [here](https://github.com/abacus-network/abacus-monorepo/blob/29970fe326079b68bb20299a450b6263d3ab32af/rust/config/test/test1_config.json#L18)) is automatically populated by our deploy tooling to include the important wallet names, and that this has so far been a manual process. We should update `writeRustConfig` in the `infra` package to ensure that upon deploying contracts and generating rust configs, the `metricsConf` is created: https://github.com/abacus-network/abacus-monorepo/blob/main/typescript/infra/src/core/deploy.ts#L10

**Comment by asaj** [comment]
@mattiecnvr is working on automagically populating the metricsConf from within the agent code, updating the ticket accordingly

**Comment by asaj** [comment]
What we should actually be doing is automatically setting the metrics confs from within the agents, since they already have all the information they need.

The two things we want to set:
- contract names, for human readability (this ticket)
- relayer wallets (#452)
