### ISSUE TITLE
Implement `MultiProvider` remote message processing hooks / blocking

### ISSUE THREAD

**Issue by yorhodes** [abacus-network/abacus-monorepo#590]
See https://discord.com/channels/935678348330434570/961710804011458621/985995524756889661 for context
Create a simple interface for developers to pass in a (source chain) transaction receipt and block on (destination chain) message processing or register an event subscription
We can check for `event Dispatch(uint256 indexed leafIndex, bytes message)`, derive the `messageHash`, and then subscribe to `event Process(bytes32 indexed messageHash)` emissions on the destination chain

**Comment by jmrossy** [comment]
Do you want to do this via an ethers provider or a block explorer?
