### ISSUE TITLE
Easily compare two validators signed checkpoints

### ISSUE THREAD

**Issue by nambrot** [abacus-network/abacus-monorepo#591]
One factor to consider for the enrollment is to check whether their signed checkpoints match another validators checkpoints. It should be relatively easy to write a small rust agent tool that takes checkpoint syncer configurations and matches them

**Comment by yorhodes** [comment]
@nambrot was this closed in https://github.com/abacus-network/abacus-monorepo/pull/803 ?

**Comment by nambrot** [comment]
yes
