### ISSUE TITLE
Research safe consensus finality parameters for mainnet chains

### ISSUE THREAD

**Issue by nambrot** [abacus-network/abacus-monorepo#596]
Someone should give do a survey of safe finality parameters that stakeholders like developers and validators can use to consider transactions on a chain final.

**Comment by nambrot** [comment]
These seem to be L0's parameters https://layerzero.gitbook.io/docs/technical-reference/mainnet/default-config

**Comment by nambrot** [comment]
Ethereum:
- Binance only does 2 confirmations for withdrawals https://www.binance.com/en/support/announcement/360030775291
- FTX does 10 for deposits and more for withdrawals https://help.ftx.us/hc/en-us/articles/360043065054-Crypto-Deposits-and-Withdrawals
- Coinbase does 35 confirmations https://help.coinbase.com/en/coinbase/getting-started/crypto-education/glossary/confirmations
-

**Comment by tkporter** [comment]
I think we need to be wary of exchange confirmations (mostly thinking of Binance's move here, which feels extremely suspicious) because they have the ability to undo deposits or trades if a reorg does end up occurring

**Comment by nambrot** [comment]
Yeah I'm mostly trying to consider withdrawals which presumbly they can't undo

**Comment by tkporter** [comment]
Generally LGTM. I'm a bit surprised that LZ has gone with 20 for arbitrum / optimism and a higher value for Avalanche. Wondering if we should try to get in contact with the core devs at those chains for extra confirmation
