### ISSUE TITLE
Document/highlight existing Abacus Messaging API

### ISSUE THREAD

**Issue by nambrot** [abacus-network/abacus-monorepo#666]
Goals:
- Focus on the API and deemphasize the framework
  - Restructuring Docs 
  - SDK namespacing
- Implement Hook

Tasks:
- #816 
- https://github.com/abacus-network/abacus-monorepo/issues/850
- https://github.com/abacus-network/abacus-monorepo/issues/852
- https://github.com/abacus-network/issues/issues/89
- https://github.com/abacus-network/issues/issues/99
- #894
- #854 
- #895
- #896
- #897
- #898

Our current work has focused on reducing the friction in developing, testing and deploying a new end to end cross chain application. However there are two issues:
- Developers with existing applications are unlikely to be able to use these abstractions completely
- While IMO still very useful, these abstractions impose a steeper learning curve, and we may "lose developers earlier in the funnel" as they won't have a success experience earlier, making them more likely to churn.

Those issues combined lead us to consider an experience that gives developers a lower-abstraction, quicker path to success.

There are several possible solutions (of which we can do all or none of them):

### Etherscan only
To highlight the simple API, we could deploy some basic recipients on all chains and then allow developers to send messages to them from Etherscan on the Outbox.
Pros:
- Simple, requires virtually no work on the developer side
Cons:
- How is gas paid for?

### Basic contract/foundry
Just calling a transaction with Metamask might not be "meaty" enough for developers to consider a success, so maybe an incredibly simple (even simpler than HelloWorld) contract template that a developer can deploy (with maybe foundry) is a better accomplishment for the developer.

Pros:
- Requires developer to be comfortable deploying a contract on at least two chains
Cons:
- How is gas paid for?

### Deploy your own version of helloworld
Before even going into the abstractions, maybe the guide should just show you the basic commands of how to run tests, but then crucially, deploy on testnet or mainnet and have messages be sent back and forth. It would be good to be able to deploy on a subset of networks.

Pros:
- Not much additional work necessary
- Onboard developers onto the abstraction
Cons:
- What is actually happening may actually be too hidden from the developer

**Comment by asaj** [comment]
If a goal is to see feedback that the message was processed (or not) we probably need some degree of observability tooling...

**Comment by asaj** [comment]
Simplest thing I can think of:

We deploy a contract on every chain that will receive messages and emits a `Received(origin, sender, message)` event.

We create a repo that folks can clone that consists of a single script. This script takes as input a source chain, destination chain, private key, and a message, and calls `Outbox.dispatch()` accordingly.

The script prints out a link to the dispatch tx on etherscan, and polls the destination chain for the process event, and prints out a link to the process tx.

We can use the public RPC nodes by default.

Open question is mainly how is gas paid for? Two issues here:
1. We don't have a griefing resistant relayer yet
2. The interchain gas calculator is possibly too tied up with our app abstraction
