### ISSUE TITLE
Metrics and alerting improvements

### ISSUE THREAD

**Issue by mattiecnvr** [abacus-network/abacus-monorepo#694]
Next iteration of fixes/improvements we came up with after @webbhorn and I went over going over the current state:

- [x] #711
  - [x] fix domain name
  - [x] deploy changes
  - [x] create alert on low balances
  - [x] #763
- [x] #739
  - [x] #744
  - [x] #745
  - [ ] deploy changes
- [x] #762
- [x] abacus-network/issues#95
- [ ] Why is there `unknown` in the last_known_message_leaf_index remotes dispatch phase
- [x] update alerts/dashboards for webb's changes
- [ ] Fix messages sent counts because indexes by remote are illogical (add new counter?)
- [ ] Test metrics (chaos engineering ?)
    - If there are messages being added to the outbox but we crash all validators will we eventually alert
- [ ] New metric for tracking delivered message index
- [ ] Create alert to track messages that have been sent but not delivered
- [x] Add more descriptions to widgets
- [ ] Add documentation for old metrics

**Comment by nambrot** [comment]
I would probably consider the first one out of scope and focus more on the operations of the topping up of the relayer scripts.

**Comment by mattiecnvr** [comment]
Ah, yes, I meant to update that. Had just copied and pasted from earlier notes. Thanks for reviewing @nambrot

**Comment by nambrot** [comment]
- Add descriptions

**Comment by mattiecnvr** [comment]
Moving this back for now since some of the bullets left here I think are lower priority. Kinda an issue with having a mega ticket like this and we might want to split off those into their own things if we care.

**Comment by nambrot** [comment]
Should we just close this for now?

**Comment by mattiecnvr** [comment]
Yes
