### ISSUE TITLE
Kathy asserts message processing

### ISSUE THREAD

**Issue by nambrot** [abacus-network/abacus-monorepo#745]
Blocked on #590

Kathy should undergo the following changes:

- Kathy should do a single message per invocation and should determine origin/destination modulo the current time (likely will need to pass through the invocation interval to cycle through) 
- Sending a message should emit a structured log line like `{ message: "Kathy Message Sent", from: "alfajores", to: "kovan", leafIndex: 123 }`
- Should use the functionality in #590 to wait for processing of each message, but timeout after some reasonable global value (maybe like 10 minutes?). Output another structured log line in both success and failure cases
- At the end of the script, make a call for each pair of networks and call `app.stats` and output a structured log line a la `{ message: "Kathy Message Stats", from: "alfajores", to: "kovan", sent: 1, received: 1 }`
- Set gauges with those stats and forward them to Prometheus/Grafana

**Comment by tkporter** [comment]
Not sure how I feel about:
```
Kathy should do a single message per invocation and should determine origin/destination modulo the current time (likely will need to pass through the invocation interval to cycle through)
```

What's the rationale? This feels like it'll add some weird complexity at the infra level to make sure that we do each pairwise chain

**Comment by mattiecnvr** [comment]
@tkporter The idea was to spread out the checks over a longer period of time. module current time I interpret to mean not a random number generator but more of mod the hour or something so we know we get through all of them if we run hourly but are constantly sending checks.

**Comment by mattiecnvr** [comment]
> Kathy should do a single message per invocation and should determine origin/destination modulo the current time (likely will need to pass through the invocation interval to cycle through)

I do disagree now that I am reading this more closely, Kathy should not send a single message per invocation but rather either
1) send a single message to each of the remotes per invocation, the source is is what should change modulo the time
2) send a single message from each of the sources per invocation, the destination is what should change modulo the time

@nambrot @tkporter 
Thoughts?

**Comment by nambrot** [comment]
Would you mind expanding on why you disagree? The intention was to incorporate @webbhorn's idea of spreading out the messages that we send so that we cover a larger time period.

**Comment by mattiecnvr** [comment]
If we really want to go to a very drawn out model, we should make kathy a service and not a cron job. It takes a enough time to spin up pods and it will be hard for us to make sure we are actually going through all of the messages with the modulus op in an orderly way. I never understood @webbhorn s idea to be sending only one message per invocation.

**Comment by mattiecnvr** [comment]
After the discussion at standup, migrating to a service model.

**Comment by mattiecnvr** [comment]
@tkporter Can you help me with transitioning the infra configs for this to a service?
