### ISSUE TITLE
Alerts that track pod restarts should use kube_pod_container_status_restarts_total

### ISSUE THREAD

**Issue by tkporter** [abacus-network/abacus-monorepo#782]
Atm, the pod restart alert query counts how many times a pod's `container_cpu_usage_seconds_total` has been reset in a provided time period. This does accurately count how many times a pod has started up, but it also considers "normal" operational behavior as a restart, e.g. when a deployment results in the pod being recreated, which we ideally shouldn't consider in the alert condition. I've already unintentionally fired the alert just with normal operations from deploying :(

Luckily we already have `kube_pod_container_status_restarts_total` handy, which counts the number of restarts a pod has had in its lifetime, which only occurs in situations where the pod crashes and is restarted. E.g. see this [Explore query](https://abacusworks.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-abacusworks-prom%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22kube_pod_container_status_restarts_total%7Bpod%3D%5C%22arbitrum-abacus-agent-validator-0%5C%22%7D%22,%22editorMode%22:%22code%22,%22range%22:true,%22instant%22:true,%22legendFormat%22:%22%7B%7Borigin%7D%7D%20-%3E%20%7B%7Bremote%7D%7D,%20%7B%7Bpod%7D%7D%22%7D%5D,%22range%22:%7B%22from%22:%22now-2d%22,%22to%22:%22now%22%7D%7D)

**Comment by mattiecnvr** [comment]
OH, yes, this makes sense, just didn't know about the metric
