### ISSUE TITLE
Add arbitrum, bsc, and optimism to the domain_and_chain lookup

### ISSUE THREAD

**Issue by tkporter** [abacus-network/abacus-monorepo#786]
Noticed when looking at the "dispatch" phase of the `abacus_last_known_message_leaf_index` metric, there are "unknown" origins, and no arbitrum, bsc, or ethereum origins. It seems like the reason why ethereum isn't there is just that there are no messages destined for ethereum yet (which makes sense, bc kathy till now has been ignoring ethereum). However it's clear that bsc, arbitrum, and optimism are not present in the domain and chain lookup declared [here](https://github.com/abacus-network/abacus-monorepo/blob/main/rust/abacus-core/src/chain.rs#L75). We should add these networks so that they aren't considered "unknown"

**Comment by webbhorn** [comment]
https://github.com/abacus-network/abacus-monorepo/pull/812
