### ISSUE TITLE
Unindexed messages should be able to be identified without future messages being indexed

### ISSUE THREAD

**Issue by tkporter** [abacus-network/abacus-monorepo#796]
With `finding_missing` mode and with this PR https://github.com/abacus-network/abacus-monorepo/pull/795 that refactors message indexing, if we index a block range [A,B] that is either empty or deemed "valid", it's still possible for messages in that range to have been skipped. If it's deemed valid, it means that there are messages with indices [N,M] that are a valid continuation from the previous last indexed message index `N-1`, but it's possible there are messages whose indices are > M that are in that [A,B] range. The existing implementation requires message indices to be able to understand if a message has been skipped. If there are no messages to extrapolate from, then the current implementation must wait until a future block range [C,D] where messages are finally indexed, and only then it can look at the indices of those messages, compare them to the last message index it previous indexed, and determine if any messages have been skipped.

This is bad because we don't have very frequent usage on some chains, and ultimately our indexing should be as robust as possible.

Copying some messages from Discord describing the solution we want:

the relayer performs eth_getLogs sliding window block ranges that never overlap. So first it'll do [A,B], then [B + 1, C], etc. It will index up to the *finalized* tip, so `eth_getBlockNumber - reorg period`

So at the moment if the finalized tip is 100, the relayer would index:
[0,100] <- catches up to the finalized tip
[101, 101] <- upon seeing that the finalized block number is 101, now it will index 101
[102, 102] <- upon seeing that the finalized block number is 102, it does 102
... etc

The problem is that sometimes we'll ask the node for [0,100] and the node may actually think the latest block number is block 99, so it only returns the logs in the range [0,99], but in our indexer we think we've indexed block 100

So my suggestion is to do the following, e.g. again if the finalized tip is 100 and the min window size is 50, the relayer would index:
[0,100] // <- catches up to the finalized tip
[51, 101] <- upon seeing that the finalized block number is 101, now it will index 101, but the minimum window size is 50, so the start block is 51
[52, 102] <- upon seeing that the finalized block number is 102, it indexes up to 102, starting with block 52

50 is probably rather high, just using it to illustrate what I mean. Event indexing is idempotent so there's no concern of getting the same events returned multiple times in these eth_getLogs RPCs. It'd be the same total # of RPCs anyways and I don't think we should care too much about conserving work for the RPC provider

On identifying dupes:

for messages it can identify dupes easily based off message indices, for gas payments it looks at the tx hash of the transaction with the event and index of the event within the transaction to determine if it's been indexed before

Concretely, we should:
* implement the above proposal in both the outbox and IGP syncer
* choose a minimum range size - something like 20 may be appropriate. Better to overestimate than underestimate here
* make extra sure the outbox and IGP syncers handle duplicates appropriately as we expect they do

----

Some old ideas:
* Query the Outbox contract occasionally to get the `Outbox.count() - 1` and ensure that it's equal to the latest indexed message index. I think this will be kinda hard in practice. My leading theory for why we miss messages is because we index to the tip of the blockchain, which is determined by an `eth_getBlockNumber` RPC minus the # of blocks to finality for the chain. We've already seen painful race conditions like this where chains with a low # of blocks to finality and a fast block time (like Arbitrum or Optimism) are especially susceptible to a situation where we query an RPC provider for block number B, and upon requesting something at that specific block, the request is load balanced to a different node that isn't aware of block B yet. `eth_getLogs` RPC implementations seem to happily handle `toBlock` values that are in the future without indicating whether or not the `toBlock` value was too far in the future or not. (A better explanation can be see in PR https://github.com/abacus-network/abacus-monorepo/pull/797). Anyways, if we were to query the Outbox count at the `to` block in the range being indexed, what happens if we get an error because our request was then load balanced to a node that's not caught up to B yet? Maybe just re-index the range, or poll the RPC provider until we get a successful Outbox.count()?
* We could try re-indexing blocks twice or something, possibly by choosing ranges that overlap (e.g. range [0,100], then [50, 150], etc). This ofc doesn't have a strong guarantee of actually finding all events
* Another idea is if we index block range [0,100] and the latest message in that range was at block 80, we start indexing the next range from 81 instead of 101. This has a slightly stronger guarantee of actually finding all events

I think the first idea is probably the most promising, but it's still rather specific to message indexing and we won't be able to make use of it when indexing GasPayment events. That's not to say we shouldn't do it, I only say this to mention that it'd be nice to have a catch-all solution that works regardless of the event

**Comment by asaj** [comment]
The last idea feels the most robust to me, can you talk through its downsides?

**Comment by tkporter** [comment]
Also only really makes sense if the theory around RPC load balancing is the real issue and that we'll never be given messages [a,c] if the messages in the requested block range are actually [a,b,c]. But at this point I'm pretty confident in the RPC load balancing theory

**Comment by tkporter** [comment]
What if we have two contract syncers running at a time, one to the "tip" and the other following a number of blocks behind looking for any missed events? Similar to what we're doing for the message explorer scraper
