### ISSUE TITLE
Deploy new HelloWorld contracts on testnet2 and mainnet using IGPs

### ISSUE THREAD

**Issue by tkporter** [abacus-network/abacus-monorepo#817]
Dependency: #755 

It seems like the existing HelloWorld contracts were deployed before we changed the IGP interface. We should:
* deploy new HelloWorld contracts that use the recently deployed IGPs
* Update helloworld-kathy to use the new contracts & IGP-related work

**Comment by asaj** [comment]
Trying to figure out what I need to do concretely in order to do this.

1. Run the helloworld deploy script for ENV
2. Update ENV/helloworld/addresses.json
3. Run the deploy-kathy script for ENV

Is that right? @tkporter anything I'm missing?
