### ISSUE TITLE
agents should be able to use a quorum of multiple providers

### ISSUE THREAD

**Issue by nambrot** [abacus-network/abacus-monorepo#832]
Invetigate the effort/complexity and cost to use a quorum of providers

**Comment by yorhodes** [comment]
https://docs.rs/ethers/latest/ethers/providers/struct.QuorumProvider.html

**Comment by yorhodes** [comment]
also available in ethers-js https://docs.ethers.io/v5/api/providers/other/#FallbackProvider for use in kathy

**Comment by asaj** [comment]
I'm thinking the work to do this would look like:
1. Update the code in rs/ts that ultimately creates providers from secret manager to accept a list of comma separated values, and create an equally weighted Quorum/Fallback provider from that
2. Upgrade testnet2
  a. Push the new code to, in order, relayer funder, kathy, validators, relayers
  b. Update each secret to be a list of 3 RPC urls
  c. Adopt the new secrets in the same order as (a)
3. Upgrade mainnet

Feels like it should be relatively straightforward, assuming these classes work as we expect them to

**Comment by asaj** [comment]
Unfortunately it does look like there are some bucks in FallbackProvider that may result in it failing when a single RPC provider is failing:
https://github.com/ethers-io/ethers.js/issues/2837
https://github.com/ethers-io/ethers.js/issues/2030

**Comment by tkporter** [comment]
Copying thoughts from Discord:

If we want to avoid needing to move ts / rs over at the same time, we could create new GCP secrets like mainnet-quorum-rpc-endpoints-celo or something that are the comma separated ones, and just move them over one at a time to that new one.
Might offer flexibility anyways if we think we may not always want a Quorum/Fallback provider

My only worry is if the provided QuorumProvider isn't as robust as we'd expect in practice / proves hard to work with. A situation that comes to mind is if you send an eth_sendTransaction / eth_sendRawTransaction to providers A, B, and C, it's possible for it to first go to A, A gossips the tx to the mempools of B and C before the RPC is processed by B and C, and then B and C both return a "tx already in mempool" error or something like that. If we're configured for a 2/3 quorum, would that cause issues?

As for the scope of code that we'd touch, I think it's relatively modest

**Comment by yorhodes** [comment]
I have been using https://github.com/yorhodes/rpc-benchmarks to minimally test the ethers-js fallbackprovider
Adding ethers-rs now
