### ISSUE TITLE
Kathy should be more resilient to transient issues

### ISSUE THREAD

**Issue by nambrot** [abacus-network/abacus-monorepo#837]
Temporary issues like nonce reuse or provider issues cause "kathy" to be marked as failed. We should have a simple retry mechanism to smooth those over

**Comment by mattiecnvr** [comment]
Retrying is done at a lower level, so this ended up getting rolled back after making some changes to that retry logic to match rust.

**Comment by nambrot** [comment]
Just want to note that nonce issues are not retryable at the provider level, but maybe that is ok once we dont reuse the key
