### ISSUE TITLE
Creater lighter mock mailbox contracts for use in testing without framework

### ISSUE THREAD

**Issue by yorhodes** [abacus-network/abacus-monorepo#854]
It should be possible to mock the system without use of peripherals for [indexing dispatch events like the current mocks require](https://github.com/abacus-network/abacus-monorepo/blob/e5a72eaba2d170fa8d97f0a9bf3f5a1832f8d89d/typescript/sdk/src/core/TestCoreApp.ts#L67) 

Pseudocode provided below. This ticket should also encompass documenting the use of these mocks.

```solidity
contract MockOutbox {
  MockInbox inbox;
  function dispatch(msg) {
    inbox.pushMessage(msg)
  }
}

contract MockInbox {
  Message messagesQueue[];
  MockOutbox outbox;
  function pushMessage(msg) onlyOutbox {
    messagesQueue.push(msg);
  }
  function processNext() {
    Messages msg = messagesQueue.pop();
    handle(msg);
  }
  function processAll() {
    while (messagesQueue.length > 0) {
      processNext();
    }
  }
  function process(msg) {
    ...
  }
```

**Comment by nambrot** [comment]
https://app.gitbook.com/o/Pl1c4GYUuMTxkQTcVCdO/s/txBgnfaTTXdfvy9mVao2/~/changes/ZBJZC5wRvEjcTAzvdjyr/developers/messaging-api/unit-testing
