### ISSUE TITLE
abacus_stored_messages metric may be wrong

### ISSUE THREAD

**Issue by mattiecnvr** [abacus-network/abacus-monorepo#865]
Currently the code does this:
https://github.com/abacus-network/abacus-monorepo/blob/766b8ac72348e9857f1ffd8c13c06f9740945096/rust/abacus-base/src/contract_sync/interchain_gas.rs#L76

to update the stored messages gauge, but this is technically not recording the number of events in the DB but rather just the number we think we have written. I suspect there are cases were we could end up thinking we wrote more than are actually in the database due to overwriting.

**Comment by mattiecnvr** [comment]
@nambrot Assigning you for prioritization and deciding if we care.

**Comment by nambrot** [comment]
I think that is ok. I assume we mostly use that metric to indicate the rate of ingestion, and the indexer is generally written to only index a range once

**Comment by nambrot** [comment]
I would probably close this for now, though in the future if we care about this we can just return the number of actual writes
