### ISSUE TITLE
Additional developer docs restructuring

### ISSUE THREAD

**Issue by yorhodes** [abacus-network/abacus-monorepo#893]
https://docs.useabacus.network/abacus-docs/developers/
is missing sections in followup to #850 

Introduction Section:
* Landing Page
  ** Landing page is a page in the Introduction section that is directory page pointing to 
      *** Developers - Getting Started
      *** Protocol - Overview
      *** What is Abacus? - page

Developers Section
* Messaging API
** Quickstart https://github.com/abacus-network/issues/issues/89
** Send
*** Interface
*** Example usage
** Receive
*** Interface
*** Example usage
** Mocks/Test https://github.com/abacus-network/abacus-monorepo/issues/854

* FAQ

* App Framework
** Quickstart
** Smart Contracts Libraries
*** deprecate hardhat plugin
** Deployment

**Comment by nambrot** [comment]
Closing in favor of #894, #895, #896, #897
