### ISSUE TITLE
Rearrange the Messaging API subsection

### ISSUE THREAD

**Issue by nambrot** [abacus-network/abacus-monorepo#895]
- Partially blocked on #894
- Partially blocked on https://github.com/abacus-network/issues/issues/99

Rearrange the `Messaging API` subsection of the `Developers` section to the following structure:

Messaging API
** Quickstart https://github.com/abacus-network/issues/issues/99
** Send
*** Interface
*** Example usage
** Receive
*** Interface
*** Example usage
** Mocks/Test https://github.com/abacus-network/abacus-monorepo/issues/854

**Comment by yorhodes** [comment]
https://app.gitbook.com/o/Pl1c4GYUuMTxkQTcVCdO/s/txBgnfaTTXdfvy9mVao2/~/changes/uAOSrQv0UQgiul1LQJqO/developers/messaging-api
