### ISSUE TITLE
Rearrange the Abacus Framework Subsection

### ISSUE THREAD

**Issue by nambrot** [abacus-network/abacus-monorepo#896]
Abacus Framework
** Quickstart
** Smart Contracts Libraries
*** deprecate hardhat plugin
** Deployment

We should make it clear that our framework is heavier weight and has a learning curve, but also list the benefits of using the framework.

**Comment by yorhodes** [comment]
https://app.gitbook.com/o/Pl1c4GYUuMTxkQTcVCdO/s/txBgnfaTTXdfvy9mVao2/~/changes/uAOSrQv0UQgiul1LQJqO/developers/building-applications
