### ISSUE TITLE
Introduction Landing page

### ISSUE THREAD

**Issue by nambrot** [abacus-network/abacus-monorepo#897]
The current landing page is mostly some softer vision stuff of Abacus when the primary visitor may not have been a developer. We should add an explicit landing page that acts as a directory and points the visitor (the primary one being a developer) to the relevant pages

Landing Page
** Landing page is a page in the Introduction section that is directory page pointing to
*** Message API 
*** Abacus Framework
*** Protocol - Overview
*** What is Abacus? - page

**Comment by asaj** [comment]
@nambrot why doesn't this match #893?
