### ISSUE TITLE
Improve Kathy's delivery detection

### ISSUE THREAD

**Issue by mattiecnvr** [abacus-network/abacus-monorepo#922]
Currently we have been seeing a lot of block skew errors that seem to be the result of providers switching our connection between instances in the backend and leading to a 1000+ block shift suddenly. This causes ethers-js to not notify us if the event we were watching for was emitted within one of the blocks that was jumped past.

A solution to this is to add an additional query to see if the event has been submitted to the inbox contract at the timeout point as a final check to prevent false error reports.

One thing we should keep in mind is that there is a memory leak here because the `.once` that is used to watch for the event will never be triggered and over time the number of filters being run will increase. I am not sure if we should worry about this at this time, but generally JS does not have a way to cancel promises so we have been potentially leaking as it stands for any of the query that never actually resolve.

**Comment by nambrot** [comment]
Changing the scope to check for the on-chain state
