### ISSUE TITLE
Pagerduty keep alert firing even after trigger stops

### ISSUE THREAD

**Issue by mattiecnvr** [abacus-network/abacus-monorepo#939]
Some of our alerts are from very discrete events and we don't want to stop the pager duty alert until a human has verified it is working now.

E.g. with the Kathy failure alert we want the grafana alert to fire for as little time as possible so that it can trigger multiple times if multiple failures happen (whereas with a 30min trigger it is very possible that the alert will have been resolved in pager duty but a new message will fail and we will miss that).

Now that we have reduced the number of errors that actually happen it is probably fine if we just increase the duration in grafana so escalation can happen correctly in pagerduty, but it would be better IMO if we can get pagerduty to keep the alert firing on its side even if grafana stops firing for some of our alerts.

(An example of where this is not the desired case is with the no blocks observed for 5min alert, because as soon as we start observing them again we are in the clear)

**Comment by nambrot** [comment]
Closing this by creating multi-dimensional alert rules
