### ISSUE TITLE
Quickly host the debugging script

### ISSUE THREAD

**Issue by nambrot** [abacus-network/abacus-monorepo#941]
@tkporter created a very helpful script that helps developers debug their message sends. Until the Message Explorer #442 is live, we should quickly host this script.

I.e. there should be a repl.it (or equivalent) that:
- Has a single textbox for a transaction hash and a dropdown for a origin chain selection
- Upon submission, it runs the script and writes the output to some text element

Script: https://github.com/abacus-network/abacus-monorepo/pull/936

**Comment by tkporter** [comment]
Only thing to note is the atm the entire error from ethers is logged here: https://github.com/abacus-network/abacus-monorepo/pull/936/files#diff-47646e8f9f034f293cccf5338697c52673c6059b820890e1f2d55cb757584175R144

There may be a more friendly way of surfacing the revert message from that error. I've had some experiences with different chains / rpc providers where the revert message is formatted differently so I didn't try to do anything fancy, but Rossy if you happen to know better ways of extracting the revert message it may be worth looking into briefly.

**Comment by jmrossy** [comment]
Script is live here: https://replit.com/@jmrossy/AbacusMessageDebugger?v=1
